(() => {
const videos=[{"id": "_3O1bCG4_q0", "title": "TWS Performance 01"}, {"id": "3DquvjT58kc", "title": "TWS Performance 02"}, {"id": "wFUYkq7-MdQ", "title": "TWS Performance 03"}, {"id": "SBuAzAa_Z6M", "title": "TWS Performance 04"}, {"id": "ZuwrrKm3-LY", "title": "TWS Performance 05"}, {"id": "tMp87orWS_Y", "title": "TWS Performance 06"}, {"id": "xiNVE_38C14", "title": "TWS Performance 07"}, {"id": "Vsg5RdTX4vs", "title": "TWS Performance 08"}];
const loader=document.getElementById('siteLoader');const hideLoader=()=>loader?.classList.add('hide');if(sessionStorage.getItem('v35Loader')==='1')hideLoader();else{window.addEventListener('load',()=>setTimeout(()=>{hideLoader();sessionStorage.setItem('v35Loader','1')},700));setTimeout(hideLoader,2200)}
const header=document.getElementById('siteHeader');window.addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>20),{passive:true});
const menu=document.getElementById('menuDrawer'),toggle=document.getElementById('menuToggle');const openMenu=()=>{menu?.classList.add('open');menu?.setAttribute('aria-hidden','false');toggle?.setAttribute('aria-expanded','true');document.body.classList.add('no-scroll')};const closeMenu=()=>{menu?.classList.remove('open');menu?.setAttribute('aria-hidden','true');toggle?.setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll')};toggle?.addEventListener('click',()=>menu?.classList.contains('open')?closeMenu():openMenu());document.querySelectorAll('[data-close-menu]').forEach(x=>x.addEventListener('click',closeMenu));document.querySelectorAll('.velocity-mobile-links details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('.velocity-mobile-links details').forEach(o=>{if(o!==d)o.open=false})}));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
let mi=0;const menuImg=document.getElementById('menuPerformanceImage'),menuTitle=document.getElementById('menuPerformanceTitle');if(menuImg&&videos.length)setInterval(()=>{mi=(mi+1)%videos.length;menuImg.src=`https://i.ytimg.com/vi/${videos[mi].id}/hqdefault.jpg`;if(menuTitle)menuTitle.textContent=videos[mi].title},4000);
const modal=document.getElementById('videoModal'),player=document.getElementById('videoModalPlayer'),modalTitle=document.getElementById('videoModalTitle');const openVideo=(id,title)=>{if(!modal||!player)return;if(modalTitle)modalTitle.textContent=title||'Performance Video';player.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${id}?autoplay=1&rel=0" title="${title||'TWS Performance'}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')};const closeVideo=()=>{modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');if(player)player.innerHTML='';document.body.classList.remove('no-scroll')};document.querySelectorAll('[data-video-id]').forEach(b=>b.addEventListener('click',()=>openVideo(b.dataset.videoId,b.dataset.videoTitle)));document.querySelectorAll('[data-close-video]').forEach(x=>x.addEventListener('click',closeVideo));
const loadMore=document.getElementById('loadMorePerformance'),gallery=document.getElementById('performanceGallery');loadMore?.addEventListener('click',()=>{gallery?.classList.add('show-all');loadMore.remove()});
document.querySelectorAll('form[data-formspree-form="true"]').forEach(form=>{const status=form.querySelector('[data-form-status]'),button=form.querySelector('button[type="submit"]'),original=button?.textContent||'Submit';const set=(type,msg)=>{if(status){status.className=`form-submit-status show ${type}`;status.textContent=msg}};form.addEventListener('submit',async e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}if(button){button.disabled=true;button.textContent='Submitting...'}set('loading','Submitting your details securely...');try{const r=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!r.ok)throw new Error();set('success','Submitted successfully.');if(form.classList.contains('tws-application-form'))location.href='application-thank-you.html';else{form.reset();if(button){button.disabled=false;button.textContent=original}}}catch{set('error','Submission failed. Please try again or contact TWS on WhatsApp.');if(button){button.disabled=false;button.textContent=original}}})});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();closeVideo()}});
})();